### ISSUE TITLE
MAUI support

### ISSUE THREAD

**Issue by mantasdaskev** [JimmyPun610/BarcodeScanner.Mobile#103]
Will this support MAUI?

**Comment by mantasdaskev** [comment]
Rephrasing :D : do you plan to support MAUI?

**Comment by JimmyPun610** [comment]
Yes, but I think it will not be so soon. (At least MAUI stable version released)

**Comment by anhhtbk** [comment]
How about progress on this issue?

**Comment by JimmyPun610** [comment]
> How about progress on this issue?

not much, the mlkit library is not quite available in MAUI at this moment

**Comment by JimmyPun610** [comment]
The Maui support is ready.
However, please be noticed that Maui is still quite unstable.
