### ISSUE TITLE
'TorchOn' does not work on some Android devices.

### ISSUE THREAD

**Issue by Ruvi1996** [JimmyPun610/BarcodeScanner.Mobile#108]
.I'm using the latest pre release of BarcodeScanner.XF which is 6.2.1.6 - Pre. I'm trying to turn on the Torch while the camera is previewing and scanning by adding a button in the camera view and setting the property 'TorchOn' to True/False. But it only works on my Samsung SM-G390F device which has Android  9 / API Level 28. I tried using several other devices such as a Samsung Galaxy Note 9 with Android 10 / API Level 29 and a Samsung Galaxy Tab A (SM-T385) which also has Android 9 but it doesn't work.

This is the output when I tried to turn on the Torch in Samsung Galaxy Tab A. The torch doesn't turn on.

```
[LegacyRequestMapper] convertRequestMetadata - control.awbRegions setting is not supported, ignoring value
[LegacyRequestMapper] Only received metering rectangles with weight 0.
[ViewRootImpl@1932dc4[MainActivity]] ViewPostIme pointer 0
[ViewRootImpl@1932dc4[MainActivity]] ViewPostIme pointer 1
[UseCaseAttachState] Active and attached use case: [androidx.camera.core.ImageAnalysis-9122cabe-f4c6-4407-8406-b0141db4f7cd190324984, androidx.camera.core.Preview-7e2eacbd-77cd-453c-853f-47def64a4116237397620] for camera: 0
[CaptureSession] Attempting to submit CaptureRequest after setting
[CaptureSession] Issuing request for session.
[RequestQueue] Repeating capture request cancelled.
[RequestQueue] Repeating capture request set.
[LegacyRequestMapper] convertRequestMetadata - control.awbRegions setting is not supported, ignoring value
[LegacyRequestMapper] Only received metering rectangles with weight 0.
```

This is the output when I tried to turn on the Torch in Samsung SM-G390F. The torch turns on.

```
[ViewRootImpl@3a508a0[MainActivity]] ViewPostIme pointer 0
[ViewRootImpl@3a508a0[MainActivity]] ViewPostIme pointer 1
[UseCaseAttachState] Active and attached use case: [androidx.camera.core.Preview-b60ea37b-3d6c-462e-8114-bd53b70450b962989428, androidx.camera.core.ImageAnalysis-c397c380-7865-410a-8bfa-f087533a9dc4194412280] for camera: 0
[CaptureSession] Attempting to submit CaptureRequest after setting
[CaptureSession] Issuing request for session.
```

**Comment by Ruvi1996** [comment]
@JimmyPun610  Appreciate if you can look into this issue.

**Comment by JimmyPun610** [comment]
Hi @Ruvi1996 ,

Unfortunately, I do not have those devices to reproduce the bug, I would suggest you add the source directly for reference to see if you could get more information. This library is using AndroidX, my guess is hasFlashUnit returning false.

The source code would be in CameraViewRenderer.cs in ./Android/Renderer
![image](https://user-images.githubusercontent.com/12612781/165872411-bd5b0e2e-d3c9-4483-9b24-ceba436ed7d7.png)

**Comment by aminm1364** [comment]
Hey there,
These methods were there on v5.0.9 and worked without any issue. since I had a building issue on iOS with this version, I upgraded it to 6.2.1.6-pre. Am I missing anything?
![image](https://user-images.githubusercontent.com/27787679/168296104-2b87c36d-503f-429b-8e7f-6732f80c5e90.png)

![image](https://user-images.githubusercontent.com/27787679/168296300-6c972344-e5ed-496b-8b6f-e04b0803bdb9.png)


Thanks in advance
Amin
