### ISSUE TITLE
GS-1 128 separator FNC1 not supported?

### ISSUE THREAD

**Issue by gioslv** [JimmyPun610/BarcodeScanner.Mobile#114]
Hi Jimmy,

I'm trying to read a GS-1 128 barcode by an android device, but the "Process" call of the IBarcodeScanner interface is not returning all the group separators (FNC1). It is showing me only the first.

For example:
[FNC1]01080328254985802112345[FNC1]1109010117100101

For this code, it is showing me only the FNC1 on the left side, but not the one on the right.
So, I can't read correctly the values, starting from the first variable AI.

Do you know something about?

I look forward to hearing from you soon

Thanks, 

Giovanni

**Comment by JimmyPun610** [comment]
Hi @gioslv ,

I am not so familiar with this type of barcode, just tried at https://barcode.tec-it.com/en/EANUCC128
According to their instruction that replacing FNC1 with \F which the data become "\F01080328254985802112345\F1109010117100101".
![image](https://user-images.githubusercontent.com/12612781/171146506-d646906a-53c6-4588-a178-e7bbbcc8d110.png)

The barcode scanner with Supporting Format Code128 will have result as below
![Screenshot_20220531-175116](https://user-images.githubusercontent.com/12612781/171146700-4dab4edf-fd04-478d-bab4-e2236f435285.png)

Is that an expected result?
