### ISSUE TITLE
The property 'TorchOn' was not found in type 'CameraView'

### ISSUE THREAD

**Issue by josephd9** [JimmyPun610/BarcodeScanner.Mobile#115]
I am trying to setup a simple project for the first time and I cannot get past this error. I have compared to the sample project and I can't see what I am missing. I am using a Xamarin Forms project if that matters. Any assistance would be wonderful! Thank you!

![image](https://user-images.githubusercontent.com/32021618/172626210-e1d8511d-c35a-4f65-9a55-feba9b5261ce.png)
![image](https://user-images.githubusercontent.com/32021618/172626295-a49c76f0-2a89-417f-9358-85c673c8169a.png)
![image](https://user-images.githubusercontent.com/32021618/172626357-b9de7d00-4f3a-4872-80c9-0e455820ba4f.png)

**Comment by JimmyPun610** [comment]
I suggest using the latest -pre version

**Comment by JimmyPun610** [comment]
> I suggest using the latest -pre version (6.2.2-pre) or move to BarcodeScanner.Mobile

**Comment by josephd9** [comment]
I changed to BarcodeScanner.Mobile.XamarinForms and got it working. Thanks!

Question though if you don't mind. 

What does isScanning and ScanInterval do? I can't find any documentation for these. Or if you can point me to where that info is that would be great!

Also, I don't see AutoStartScanning property. Was that removed? If so does that mean that the scanning has to be manually started?

**Comment by JimmyPun610** [comment]
IsScanning is property to set the camera view is scanning and analysing barcode.

Scan interval is the interval between each scan, it mainly used for blocking multiple scan because the mlkit scan the code too fast.

for autostartscanning, you can set IsScanning to true Iin XAML.
