### ISSUE TITLE
Cannot find namespace BarcodeScanner.Mobile.XamarinForms.Droid

### ISSUE THREAD

**Issue by Gaburiere** [JimmyPun610/BarcodeScanner.Mobile#116]
while setupping barcode scanner version 6.3.0.21 on Xamarin.Forms version 5.0.0.2478 debug fails because it is not possibile to init renderer for android. Namespace BarcodeScanner.Mobile.XamarinForms.Droid is not found so I can't call RendererInitializer.Init(); I've installed the nuget on shared project and platform ones.

**Comment by JimmyPun610** [comment]
What is the target framework of your Android project? Only MonoAndroid12.0 is supported in latest Xamarin Forms version

**Comment by josephd9** [comment]
I had this same issue. I had to install visual studio 2022. Then I had to restart the project because of some java.exe error. But after that I was able to get the namespace to load. Thanks!

**Comment by JimmyPun610** [comment]
> I had this same issue. I had to install visual studio 2022. Then I had to restart the project because of some java.exe error. But after that I was able to get the namespace to load. Thanks!

Oh. It seems that starting from MonoAndroid 12, visual studio 2022 is required.

**Comment by Gaburiere** [comment]
> What is the target framework of your Android project? Only MonoAndroid12.0 is supported in latest Xamarin Forms version

I was targeting android 11. Switching to 12 has resolved the issue. by the way I'm using rider 221.5080.236.
thanks for the support.
