### ISSUE TITLE
Front camera opened but it's view is very dark

### ISSUE THREAD

**Issue by Dinesh2411** [JimmyPun610/BarcodeScanner.Mobile#118]
I have installed the **6.2.2 pre-release** version of the package and wanted to implement QR Code scanning functionality using **front camera**. The scanning is working absolutely fine.

The only problem I am facing is that when the camera view opens, it shows quite a dark picture/view.
![Screenshot_2022-06-14-15-28-32-651](https://user-images.githubusercontent.com/29883153/173553018-a6e112c2-05c2-4982-89e1-5d5058f23c37.jpeg)

I am using a Lenovo tablet model Lenovo TB-X306X which has a 5MP front camera.

**Comment by JimmyPun610** [comment]
If you have manually set RequestFPS please remove it and try again

**Comment by Dinesh2411** [comment]
Great thanks this solved the problem for me. BTW must say this is a great library.
