### ISSUE TITLE
Xamarin.Android Release failed to build the project because of Unable to get provider com.google.mlkit.common.internal.MlKitInitProvider

### ISSUE THREAD

**Issue by valerii-sovytskyi** [JimmyPun610/BarcodeScanner.Mobile#122]
Xamarin android that targets Android 12 (API 31) 

**The issue:**
For my case I was not able to RUN the application on release mode, and by researching I found that the problem was next:

**Unable to get provider com.google.mlkit.common.internal.MlKitInitProvider**

To fix this issue I needed to update the AndroidManifest.xml

Just add this code

`<provider android:name="com.google.mlkit.common.internal.MlKitInitProvider" android:authorities="${your app id}.mlkitinitprovider" tools:node="remove" />
    <meta-data
              android:name="com.google.mlkit.vision.DEPENDENCIES"
              android:value="barcode" />`
And inside Manifest

`xmlns:tools="http://schemas.android.com/tools"`

I'm suggesting to update the Wiki section so developers will add it to the AndroidManifest

![image](https://user-images.githubusercontent.com/17310375/176675036-ac265562-1351-4ab7-8ed2-b127b5edb1ea.png)

_The fix found here https://developers.google.com/ml-kit/vision/barcode-scanning/android_

**Comment by JimmyPun610** [comment]
Interesting. Didn't get this error....
Anyway, I have added into wiki. Thanks a lot

**Comment by valerii-sovytskyi** [comment]
Sorry, but I didn't test it well, this fix is not working, the crash was fixed, but the Scanner is not working I guess because I removed MLKit at all, I will update you on my investigation

**Comment by valerii-sovytskyi** [comment]
@JimmyPun610 
The problem was here Android Options -> **Code shrinker** -> **not to be r8** in my case it's an empty selector.

Please, remove what I suggested.

![image](https://user-images.githubusercontent.com/17310375/176913854-3ece27e9-a097-4ced-92ca-e43218cd0301.png)
