### ISSUE TITLE
ReturnBarcodeImage=True causes OnDetected to not fire

### ISSUE THREAD

**Issue by nerriksolutions** [JimmyPun610/BarcodeScanner.Mobile#123]
Hi Jimmy,

I'm wanting to get the image back that the QR code was deciphered from... but setting ReturnBarcodeImage=True causes the following error to be logged:

**[CameraViewRenderer] System.InvalidCastException: Specified cast is not valid.**
**[CameraViewRenderer]   at BarcodeScanner.Mobile.XamarinForms.Renderer.CameraViewRenderer+BarcodeAnalyzer.GetImageRotationCorrectionDegrees () [0x00036] in <474cfd4c74cf4e748b60b96ae06b9d43>:0** 
**[CameraViewRenderer]   at BarcodeScanner.Mobile.XamarinForms.Renderer.CameraViewRenderer+BarcodeAnalyzer.Analyze (AndroidX.Camera.Core.IImageProxy proxy) [0x00225] in <474cfd4c74cf4e748b60b96ae06b9d43>:0**

Which then causes the OnDetected  to not fire.

This is also happening in the sample project

**Comment by JimmyPun610** [comment]
This should be fixed on v6.3.0.22
Both Xamarin and Maui

**Comment by nerriksolutions** [comment]
Mate your a legend! Works perfectly - Thank you!
