### ISSUE TITLE
Having trouble installing it

### ISSUE THREAD

**Issue by imsam67** [JimmyPun610/BarcodeScanner.Mobile#124]
I've tried installing your package quite a few times but I keep getting this error:

```
Severity	Code	Description	Project	File	Line	Suppression State
Error		Could not find a part of the path 'C:\Users\MyUserName\.nuget\packages\xamarin.firebase.ios.core\8.10.0.1\lib\net6.0-ios15.4\Firebase.Core.resources\GoogleUtilitiesComponents.xcframework\ios-arm64_i386_x86_64-simulator\GoogleUtilitiesComponents.framework\PrivateHeaders\GULCCComponentContainerInternal.h'.	
```

It looked like the long path issue so I enabled it through the registry on my Windows 11 machine. Even after a reboot, I still get this error.

Any suggestions?

BTW, I'm trying to use your package on a .NET MAUI app. I'm using Visual Studio 2022 17.3.0 Preview 2.0 which is the latest at the time of this question.

**Comment by JimmyPun610** [comment]
For Maui, I am not sure is the visual studio for windows is stable or not, I have to build Android by Windows but iOS by Mac...

**Comment by JimmyPun610** [comment]
or you could try to update global variable
https://github.com/xamarin/GoogleApisForiOSComponents/issues/555#issuecomment-1145943195

**Comment by michaelreinprecht** [comment]
I have ran into the same problem trying to install the BarcodeScanner.Mobile.XamarinForms nugget. I get the same exact error message when trying to install on iOS Project. Shared and Android Project working fine. 

This happened on a freshly created Xamarin Forms Blank App. VS 17.1.6.
