### ISSUE TITLE
ScanFromImage(bytes) not implemented?

### ISSUE THREAD

**Issue by mark-sheldon** [JimmyPun610/BarcodeScanner.Mobile#127]
Scanning from an image always returns null so I checked the ScanFromImage(bytes) method and found it is not implemented.

From the sample:

namespace BarcodeScanner.Mobile.Core
{
    public class Methods
    {
        public static void SetSupportBarcodeFormat(BarcodeFormats barcodeFormats)
        {
            throw new NotImplementedException();
        }

        public static async Task<List<BarcodeResult>> ScanFromImage(byte[] imageArray)
        {
            throw new NotImplementedException();
        }
    }
}

Is there a later version perhaps?

**Comment by mark-sheldon** [comment]
Never mind. Issue was on my side. It's working fine.

**Comment by JimmyPun610** [comment]
The logic is implemented in each platform, which is iOS.Methods and Droid.Methods.
It could be related to the quality / too much noise (unrelated information) of uploaded images

**Comment by mark-sheldon** [comment]
Thank you for your message.

Okay. That explains it. I just didn't find them where I expected, and when
combined with the null reference it had me scratching my head a little bit.

You are correct about the quality of the images. The problematic images
were photographs of a screen display taken on a cell phone. When I went
back and downloaded and used the actual images, the issue resolved itself.

This is a nice project. Thanks for all your hard work.

m.
