### ISSUE TITLE
Very low brightness when scanning

### ISSUE THREAD

**Issue by dima121181** [JimmyPun610/BarcodeScanner.Mobile#128]
**Describe the bug**
When I start scanning, the screen is very dark. The places where the lamps or the sun shine are vaguely visible, everything else is in darkness.

**To Reproduce**
1. Create a CameraVew:
BarcodeScanner.Mobile.XamarinForms.CameraView CVNew = new BarcodeScanner.Mobile.XamarinForms.CameraView {
                HorizontalOptions = LayoutOptions.FillAndExpand,
                VerticalOptions = LayoutOptions.FillAndExpand,
                TorchOn = false,
                VibrationOnDetected = true,
                IsScanning = true,
                RequestedFPS = 24,
                ScanInterval = 1500,
                Margin = 0
            };
2. Add CameraVew to StackLayout
4. Open Page with StackLayout with CameraView

In the GoogleVisionBarCodeScanner there was a normal bright image

**Smartphone (please complete the following information):**
 - Device: POCO X3 Pro 8/256
 - OS: MIUI Global 13.0.2 Android 12 SKQ1.211006.001
 - Version Xamarin.Forms v5.0.0.2478

![IMG_20220708_105249](https://user-images.githubusercontent.com/79144784/177945061-c3e559d2-a9a9-4de5-a378-a75321c7c404.jpg)

**Comment by JimmyPun610** [comment]
Hi @dima121181 

Did you try to remove RequestFPS property?

**Comment by dima121181** [comment]
I'll try

**Comment by dima121181** [comment]
After removing the parameter everything was fine, thanks. I deliberately set 24 frames to reduce power consumption a little. Does that mean it can't be done now?

**Comment by JimmyPun610** [comment]
> After removing the parameter everything was fine, thanks. I deliberately set 24 frames to reduce power consumption a little. Does that mean it can't be done now?

I do not think it is good idea to change it for power saving. This property will affect the exposure
https://docs.microsoft.com/en-us/dotnet/api/android.hardware.camera2.captureresult.controlaetargetfpsrange

**Comment by dima121181** [comment]
Well, on GoogleVisionBarCodeScanner, scanning at 24 fps was fine for us. But I understood. Thank you.
