### ISSUE TITLE
Scans worse than BarcodeScanner.XF

### ISSUE THREAD

**Issue by dima121181** [JimmyPun610/BarcodeScanner.Mobile#131]
**Describe the bug**
Hello. Sometimes dirt gets on the barcodes, or they are wrinkled and the old version of the scanner could still recognize them. The new version is more finicky and doesn't read some barcodes that the old version did.

**To Reproduce**
Creating a new scanner
```
            BarcodeScanner.Mobile.XamarinForms.CameraView CVNew = new BarcodeScanner.Mobile.XamarinForms.CameraView {
                HorizontalOptions = LayoutOptions.FillAndExpand,
                VerticalOptions = LayoutOptions.FillAndExpand,
                TorchOn = false,
                VibrationOnDetected = true,
                IsScanning = true,
                CaptureQuality = BarcodeScanner.Mobile.Core.CaptureQuality.Highest,
                ScanInterval = 1500
            };
```

Creating an old scanner
```
            GoogleVisionBarCodeScanner.CameraView CVOld = new GoogleVisionBarCodeScanner.CameraView {
                HorizontalOptions = LayoutOptions.FillAndExpand,
                VerticalOptions = LayoutOptions.FillAndExpand,
                DefaultTorchOn = false,
                VibrationOnDetected = true,
                AutoStartScanning = true,
                RequestedFPS = 30,
                ScanInterval = 1500
            };
```

**Expected behavior**
Barcodes from screenshots are read in the old scanner, but are not read in the new one.

**Screenshots**
![WhatsApp Image 2022-07-29 at 13 45 33](https://user-images.githubusercontent.com/79144784/182147114-3e4e5aac-8646-439e-a543-d6ced437104f.jpeg)
![WhatsApp Image 2022-07-29 at 13 47 00](https://user-images.githubusercontent.com/79144784/182147123-1542ddf3-f5f4-4e1d-aead-e4f5b3dcdf76.jpeg)

**Smartphone (please complete the following information):**
 - Device: POCO X3 Pro 8/256
 - OS: MIUI Global 13.0.2 Stable
 - Version old scanner package: BarcodeScanner.XF 5.0.9
 - Version new scanner package: BarcodeScanner.Mobile.Core 6.3.0.21, BarcodeScanner.Mobile.XamarinForms 6.3.0.22
 - Version XamarinForms: XamarinForms v5.0.0.2515

**Comment by JimmyPun610** [comment]
Hi @dima121181 ,

Sorry, there is nothing I can do on the recognition of the barcode as it is MLKit Barcode Scanning logic from Google and there are only version upgrade in the package.
In fact, I tried to scan the barcode you provided by different tools (ZXing, Scandit..etc) and they are also not recognizing the barcode.

I could only suggest you set the barcode format on the scanning.

**Comment by dima121181** [comment]
Understood. Thanks for the answer.
