### ISSUE TITLE
Support for older Android versions for MAUI

### ISSUE THREAD

**Issue by mantasdaskev** [JimmyPun610/BarcodeScanner.Mobile#132]
**Is your feature request related to a problem? Please describe.**
The problem is that I cannot build this project with minimum Android API 24 version. It makes app usable only with Android 12 and above if I want to use BarcodeScanner.

**Describe the solution you'd like**
I would like to use this nuget with lower android versions.

**Comment by mantasdaskev** [comment]
Tested with just lowering minimum level to 24 and at least camera view works. I'll post the results with scan test.

**Comment by JimmyPun610** [comment]
Actually I just plan to support the latest 3 versions for Android and iOS at all.
Good to hear you that it is working in Android 7

 closed
