### ISSUE TITLE
package does not exist error in Maui App

### ISSUE THREAD

**Issue by HobDev** [JimmyPun610/BarcodeScanner.Mobile#134]
**Describe the bug**
package does not exist error in Maui App. The number of bugs is 38. All the missing packages start from `com.google.android.gms`

**To Reproduce**
Create new Maui App and install barcodescanner.mobile.maui. Now debug the solution.

**Expected behavior**
The app should build and run on the emulator.

**Smartphone (please complete the following information):**
 - Device: Android Emulator (Pixel 5- API-31)
 - OS: Android 12
 - Version : Visual Studio 17.3 stable version on Windows

**Comment by JimmyPun610** [comment]
Hi @HobDev 

Did you install Google play services in your Android SDK tool?

**Comment by HobDev** [comment]
Hi @JimmyPun610 
 Yes, I installed Google play services from Android SDK tool and the errors are still there.

**Comment by gkenaston** [comment]
> Hi @JimmyPun610 Yes, I installed Google play services from Android SDK tool but the errors are still there.

Check that you have this in your csproj file:

`<ItemGroup Condition="'$(TargetFramework)' == 'net6.0-android'">
    <PackageReference Include="Xamarin.Google.MLKit.BarcodeScanning" Version="116.1.2.5" />
</ItemGroup>`

**Comment by HobDev** [comment]
> Check that you have this in your csproj file:
> 
> `<ItemGroup Condition="'$(TargetFramework)' == 'net6.0-android'"> <PackageReference Include="Xamarin.Google.MLKit.BarcodeScanning" Version="116.1.2.5" /> </ItemGroup>`

The app build successfully after adding the above package in the csproj. Thank you @gkenaston

**Comment by HobDev** [comment]
The the package `Xamarin.Google.MLKit.BarcodeScanning` also required for iOS project.

**Comment by JimmyPun610** [comment]
> Does the the package `Xamarin.Google.MLKit.BarcodeScanning` also required for iOS project.

No, it is an Android binding library
