### ISSUE TITLE
Xamarin Android crash on startup after data cleared

### ISSUE THREAD

**Issue by programatix** [JimmyPun610/BarcodeScanner.Mobile#136]
**Describe the bug**
I have an existing Xamarin App (Android & iOS) which I just added BarcodeScanner.Mobile for QR Code scanning. On this app, running in Debug mode runs well until I cleared the App Data in App Info. It will then crash on start up, unable to start anymore. When I run in Release mode, it runs for a while and crashed. It happen on both my actual device and android emulator.

I tried to replicate this in a new solution and is able to replicate the issue in Debug mode. However, the Release mode runs without any issue, which I can't figure out why.

I'm using Visual Studio Pro 2022 version 17.3.0 on Windows 10.

**To Reproduce**
1. Open BarcodeScanner.sln.
2. Build using Debug profile.
3. Run/deploy to Emulator (Android 12 - API 31)
4. Grand camera permission
5. Open App Info
6. Tap Storage & cache
7. Tap Clear storage (the app will be terminated)
8. Run the app using the app shortcut
9. The app shows the splash screen, then crash
10. Uninstall app
11. Redeploy
12. The app can start again.

**Expected behavior**
The app should run without crashing.

**Smartphone (please complete the following information):**
 - Device: Android Emulator / Samsung Galaxy Note 10+
 - OS: Android 12
 - Version: XamarinForms v6.3.0.22

**Additional context**
[BarcodeScanner.zip](https://github.com/JimmyPun610/BarcodeScanner.Mobile/files/9349314/BarcodeScanner.zip)

**Comment by programatix** [comment]
I did a quick test with MAUI empty project and the issue is there too for DEBUG build.

**Comment by JimmyPun610** [comment]
Just tested a bit...
Seems that the error is only occurring when Fast Deployment is enable.

Could you disable Fast Deployment and try again to see the problem still exist?

**Comment by programatix** [comment]
Using the sample solution I provided in the zip, I unchecked ```Use Fast Deployment (debug mode only)``` and performed a debug on Android Emulator - Android 12.0 - API 31). It immediately crash upon app start up.

But if I run the app using the launcher in the emulator, the app starts up fine. The issue crashing after clearing its data also goes away. However, now I can't debug the app as it crashed on start up.

**Comment by JimmyPun610** [comment]
> Using the sample solution I provided in the zip, I unchecked `Use Fast Deployment (debug mode only)` and performed a debug on Android Emulator - Android 12.0 - API 31). It immediately crash upon app start up.
> 
> But if I run the app using the launcher in the emulator, the app starts up fine. The issue crashing after clearing its data also goes away. However, now I can't debug the app as it crashed on start up.

Sorry, I cannot reproduce the problem with my Pixel 3. Does it happening on real device?
My step
1. Uncheck Fast Deployment
2. Start and debug
3. Clear app data
4. Reopen the app

**Comment by programatix** [comment]
With "Uncheck Fast Deployment",
- I can debug with my Samsung Galaxy Note 10+ (Android 12). Clearing app data also works fine.
- It crashes on debug with Android Emulator (Android 12). Running app directly from the launcher works fine. Clearing app data also works fine.

So, it seems the workaround on unchecking "Fast Deployment" works on actual device.

However, my actual issue is the production app crashes after I added BarcodeScanner.Mobile in Release build. Perhaps it could be having some conflict with other nuget components? I was hoping that resolving this issue "may" solve the actual issue I'm having.

**Comment by programatix** [comment]
Ah, I found the cause of the crash in Release build. I have ```Code shrinker``` set to ```r8```. Unset it and Release build runs ok. Is this considered a bug or a requirement for BarcodeScanner.Mobile?

**Comment by JimmyPun610** [comment]
I would say it is a requirement to use this library...
I read some post in the Internet, it may caused by AndroidX or may be the native library...

https://github.com/xamarin/xamarin-android/issues/4908
