### ISSUE TITLE
Error when restoring nuget packages in VS 2022 on Windows

### ISSUE THREAD

**Issue by dzebas** [JimmyPun610/BarcodeScanner.Mobile#137]
**Describe the bug**

Can't restore nuget packages for Xamarin.Firebase.iOS 

**To Reproduce**

1. Create blank Xamarin.Forms project
2. Add BarcodeScanner.Mobile.XamarinForms nuget package
3. You get error "\.nuget\packages\xamarin.firebase.ios.core\8.10.0.1\lib\net6.0-ios15.4\Firebase.Core.resources\GoogleAPIClientForREST.xcframework\ios-arm64_i386_x86_64-simulator\GoogleAPIClientForREST.framework\Headers\GoogleAPIClientForREST-umbrella.h'."				
4. When I inspected this folder  (Headers) it was empty

**Expected behavior**
Should restore nuget packages without errors.

**Other info:**
 - OS: Windows 11 
 - Visual Studio 2022 v17.3.2
 - XamarinForms v5.0.0.2515

**Additional context**
Interestingly, it works fine on Mac OS with Visual Studio 2022, it restores all packages and builds OK. Only get this issue on Windows.

**Comment by JimmyPun610** [comment]
#124  #133 
Probably related to these issue

**Comment by dzebas** [comment]
Thank you, long paths on Windows 11 was the issue, solved my problem!
