### ISSUE TITLE
Camera preview is blank if RequestedFPS value is set

### ISSUE THREAD

**Issue by sukanzubair** [JimmyPun610/BarcodeScanner.Mobile#138]
**Describe the bug**
Downloaded the latest release and ran the application fine. 
If I set the RequestedFPS  in the XAML file of Page 1 and run the application. 
The camera preview is black.

I tried RequestedFPS =60 and RequestedFPS =120

**To Reproduce**

**Expected behavior**

**Screenshots**

**Smartphone (please complete the following information):**
 - Version [e.g. XamarinForms v6.3.0.22 / Maui v6.3.0.22-pre]

**Additional context**

**Comment by JimmyPun610** [comment]
RequestFPS property will only affect in Android.
If you do not sure what is the value, just remove it and it will be decided by the device.

**Comment by adrian-sal-kennedy** [comment]
this may be similar to an issue I'd encountered. In CameraViewRenderer.cs under Android, line 100 there's a check for whether RequestFPS is set, and if it is it'll set the camera to manual exposure. Depending on the room conditions when the camera is turned on this could give you a very underexposed (black) picture.

as JimmyPun610 says, you could avoid this by not attempting to set RequestFPS in android.
