### ISSUE TITLE
Camera Freeze when Back to the page with Barcode Scanner

### ISSUE THREAD

**Issue by chosokabecs50** [JimmyPun610/BarcodeScanner.Mobile#142]
Hi, sorry for asking some beginner question, but currently I am having an issues where my Scanner Page will stay freeze for this nuget package, I have tried to do with a few method that having similar issues that was shown here:  https://github.com/Redth/ZXing.Net.Mobile/issues/659, but still doesn't fix it, is there any workaround to prevent the camera freeze? Or am I missing something crucial?

![image](https://user-images.githubusercontent.com/46775982/191407277-f796df66-7c93-4669-8b5e-a44cb33c7d5f.png)

**Comment by JimmyPun610** [comment]
Are you using it in emulator or real device?

**Comment by chosokabecs50** [comment]
I have tried using both the emulator and real device, but the issue are still the same. Was wondering is it due to the camera state doesn't Open back when back to the page.

**Comment by chosokabecs50** [comment]
Hi Sure, Sorry for taking some time, not really used to using GitHub for sharing code.

Link Below are the sample code that can recreate the issues I currently having.
**
1) Click on Go to Scan Page Button.
2) Scan any Barcode on camera in 'AboutPage'.
3) At 'NewPage' , press the Back button so it will Back to 'AboutPage'.
4) Camera is now Freeze/Stuck
**

https://github.com/chosokabecs50/Barcode_Test

I have tried some workaround such as back to 'MainPage' then straight to AboutPage, however it doesn't look nice and feel buggy.

Is there anyway to solve it so that when back to the AboutPage, the Camera would still stay on active? 

Thank you so much

**Comment by JimmyPun610** [comment]
Hi @chosokabecs50 ,

After testing with your source code, what is the purpose of the camera view on the NewPage?
The problem I think is that there is 2 active camera views and only the latest one would work...
Pressing back button in Android is just going back to the previous state of the page and it will not redraw all the component.

I.E.
When you go to NewPage that has CameraView, CameraView in AboutPage (A) will be frozen because CameraView in NewPage (B) take over the Camera. And A will not resume unless you redraw the CameraView component to take over the Camera again.

Here is a workaround for your sample but I am not sure it still work in iOS..
AboutPage.xaml .cs
```C#
using Barcode_Test.ViewModels;
using BarcodeScanner.Mobile.XamarinForms;
using System;
using System.ComponentModel;
using System.Threading.Tasks;
using Xamarin.Forms;
using Xamarin.Forms.Xaml;

namespace Barcode_Test.Views
{
	public partial class AboutPage : ContentPage
	{
		public AboutPage()
		{
			InitializeComponent();
		}

		protected override void OnAppearing()
		{
			base.OnAppearing();
            Device.BeginInvokeOnMainThread(async() =>
            {
                // await a time so your camera view in NewPage is destoryed
                await Task.Delay(1000);
                this.CameraStack.Children.Add(CreateCameraView());
            });
		}

		protected override void OnDisappearing()
		{
			base.OnDisappearing();
			Device.BeginInvokeOnMainThread(() =>
			{
                this.CameraStack.Children.Clear();
			});
			
		}

		private CameraView CreateCameraView()
		{
			return new CameraView
			{
				IsScanning = (this.BindingContext as AboutViewModel).IsScanning,
				ScanInterval = 1000,
				OnDetectedCommand = (this.BindingContext as AboutViewModel).OnDetectCommand,
				HorizontalOptions = LayoutOptions.FillAndExpand,
				VerticalOptions = LayoutOptions.FillAndExpand
			};
		}
	}
}
```
AboutPage.xaml
```xaml
<?xml version="1.0" encoding="utf-8" ?>
<ContentPage xmlns="http://xamarin.com/schemas/2014/forms"
             xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
             x:Class="Barcode_Test.Views.AboutPage"
             xmlns:vm="clr-namespace:Barcode_Test.ViewModels"
             xmlns:Scanner="clr-namespace:BarcodeScanner.Mobile.XamarinForms;assembly=BarcodeScanner.Mobile.XamarinForms"
             Title="{Binding Title}">
    
    <ContentPage.BindingContext>
        <vm:AboutViewModel />
    </ContentPage.BindingContext>
    
    <ContentPage.Resources>
        <ResourceDictionary>
            <Color x:Key="Accent">#96d1ff</Color>
        </ResourceDictionary>
    </ContentPage.Resources>

    <Grid>
        <Grid.RowDefinitions>
            <RowDefinition Height="Auto" />
            <RowDefinition Height="*" />
        </Grid.RowDefinitions>
        <StackLayout BackgroundColor="{StaticResource Accent}" VerticalOptions="FillAndExpand" HorizontalOptions="Fill">
            <StackLayout Orientation="Horizontal" HorizontalOptions="Center" VerticalOptions="Center">
                <ContentView Padding="0,40,0,40" VerticalOptions="FillAndExpand">
                    <Image Source="xamarin_logo.png" VerticalOptions="Center" HeightRequest="64" />
                </ContentView>
            </StackLayout>
        </StackLayout>
        <ScrollView Grid.Row="1">
            <StackLayout Orientation="Vertical" Padding="30,24,30,24" Spacing="10" x:Name="CameraStack">
                <!--<Scanner:CameraView
                            OnDetectedCommand="{Binding OnDetectCommand}" 
                            IsScanning="{Binding IsScanning}" 
                            ScanInterval="1000"
                            x:Name="Scanner" HorizontalOptions="FillAndExpand" VerticalOptions="FillAndExpand"/>-->
            </StackLayout>
        </ScrollView>
    </Grid>

</ContentPage>

```

**Comment by chosokabecs50** [comment]
Hi @JimmyPun610,

Actually my purpose for using the Scanner on both page was to  checking up the Parcel within the huge Pallet to make sure the 'Parcel' within is correct.

'Pallet' - A huge Box that contains multiple Product
'Parcel' - product that was contained within the 'Parcel'
For eg)
1) Scan the 'Pallet' Barcode to NewPage.
2) NewPage will then list out all Parcel that was contained within the 'Pallet'
3) Scan each of the 'Parcel' Barcode to make sure all of them are correct At NewPage.
4) If all of 'Parcel' are correct, NewPage will be redirect back to AboutPage for the next 'Pallet' to scan.

So my problem is at the step 4, where the AboutPage will froze by then.

Anyway thanks for helping getting some workaround for it, it seems to work by now, for the iOS I don't think I will develop for it so no worries. Really appreciate your help 😺 😺
