### ISSUE TITLE
How to install the nuget package ?

### ISSUE THREAD

**Issue by ThomasCarltonInPerson** [JimmyPun610/BarcodeScanner.Mobile#149]
Hi team,

I'm trying to install BarCodeScanner.Mobile on visual studio using the following nuget command from [Here([url](https://www.nuget.org/packages/BarcodeScanner.Mobile.Maui/6.3.0.23-pre))

        NuGet\Install-Package BarcodeScanner.Mobile.Maui -Version 6.3.0.23-pre

The installation start but then stops after some steps showing the error : 

        Cannot find a part of the folder 'GULCCComponentContainerInternal.h'

![image](https://user-images.githubusercontent.com/67571763/198406826-272a1766-2aca-48d0-9786-02e5a5652034.png)

Does anyone know how to install the nuget package please ?

Thanks.
Regards,

**Comment by JimmyPun610** [comment]
maybe related to https://github.com/JimmyPun610/BarcodeScanner.Mobile/issues/124

**Comment by ThomasCarltonInPerson** [comment]
> maybe related to #124

Thanks Jimmy that works now.
