### ISSUE TITLE
AddBarcodeScannerHandler raises compilation error ?

### ISSUE THREAD

**Issue by ThomasCarltonInPerson** [JimmyPun610/BarcodeScanner.Mobile#150]
Hello community,

I'm trying to use the BarcodeScanner for the first time but when adding the initial code in my CreateMauiApp function I'm getting the following compilation error : 

        'IMauiHandlersCollection' doesn't contain a definition for AddBarcodeScannerHandler.

![image](https://user-images.githubusercontent.com/67571763/198882185-b5897117-8278-4ecb-9713-464849e3e9fe.png)

I tried adding the following using directive but it didn't solve the issue. 

        using BarcodeScanner.Mobile.Maui;

Does anyone know how to solve that please ?

Thanks.
Regards,

**Comment by JimmyPun610** [comment]
Hi, does the error still exist if you use 6.3.0.25?
```C#
using BarcodeScanner.Mobile;
```

```C#
handlers.AddBarcodeScannerHandler();

```

**Comment by 00zgit** [comment]
> ```cs
> handlers.AddBarcodeScannerHandler();
> ```

Hi, @JimmyPun610 
I am using version 6.3.0.25 and got the error.
