### ISSUE TITLE
Stop using the Camera

### ISSUE THREAD

**Issue by w1ck3l** [JimmyPun610/BarcodeScanner.Mobile#153]
Hey guys.

I really want to use this in my app, however, I can't find a way to disable the camera after the scan. 
I read through the Xmaarin Wiki in this repo, but still failed to find anything.

I figured CameraView.IsEnabled = false; would have done it, but it did not.

Any help would be appreciated.  Thanks!

**Comment by JimmyPun610** [comment]
Hi, what do you mean of "Disable" the camera?
Does removing the CameraView work?

**Comment by OliverDevsCodex** [comment]
Could you eventually provide some example code?  @w1ck3l

**Comment by w1ck3l** [comment]
@OliverDevsCodex 

In my Scanning.xaml.cs file

void CameraView_OnDetected(System.Object sender, GoogleVisionBarCodeScanner.OnDetectedEventArg e)
        {
            var results = e.BarcodeResults;
            var resultString = results[0].RawValue;

            //When I pop this page, I need access to the scanned information
            Xamarin.Essentials.Preferences.Set("SCAN", resultString);

            Device.BeginInvokeOnMainThread(async () =>
            {
                await DisplayAlert("Success", "Scan Successful", "OK");
            });

            Navigation.PopAsync();
        }

**Comment by comm-lab** [comment]
So, is there a way to release camera resources? I need to take a picture when I'm done scanning, so I'd like to release the camera and show another control (for example https://github.com/hjam40/Camera.MAUI) to take the picture. Would it be possibile to release the camera resources and let another view use it?

**Comment by w1ck3l** [comment]
@comm-labI can't seem to find your comment on github, so I'll respond here in e-mail.
When I was working with this, I was unable to release the camera.  I had to dispose of the view entirely.

I've recently come across a "Popup" view in the Maui Community Toolkit.I'd recommend using that to display the barcode scanner camera, and then dispose of the entire popup view.

    On Tuesday, January 23, 2024 at 11:06:42 AM MST, comm-lab ***@***.***> wrote:  
 
 


So, is there a way to release camera resources? I need to take a picture when I'm done scanning, so I'd like to release the camera and show another control (for example https://github.com/hjam40/Camera.MAUI) to take the picture. Would it be possibile to release the camera resources and let another view use it?
