### ISSUE TITLE
How can I disable it or make it work in windows platform?

### ISSUE THREAD

**Issue by lkace** [JimmyPun610/BarcodeScanner.Mobile#154]
Hey gays,

I want to make a android app and a windows app, but I can't run on windows platform because of this. (I don't need to scan in windwos platform.)

xmlns:gv="clr-namespace:BarcodeScanner.Mobile.Maui;assembly=BarcodeScanner.Mobile.Maui"
![image](https://user-images.githubusercontent.com/103358946/201274043-87c7950e-1ca9-4794-9709-5bbe71edd742.png)

**Comment by adrian-sal-kennedy** [comment]
I did this in xamarin - it just pretty much does nothing:
```
namespace GoogleVisionBarCodeScanner.UWP
{
    public class Methods
    {
        public void SetIsScanning(bool isScanning)
        {
            Debug.WriteLine("GoogleVisionBarcodeScanner is not implemented for UWP!");
        }
    }
}
```
