### ISSUE TITLE
Barcoderesult.RawValue omitting characters

### ISSUE THREAD

**Issue by afriscic** [JimmyPun610/BarcodeScanner.Mobile#156]
Hello,

when scanning GS1 Datamatrix codes Barcoderesult.RawValue does not contain special characters and is the same as DisplayValue.
For example ASCII 29 (<GS>).

Is it possible to get byte[] of the barcode or implement that RawValue is a byte[] of the scanned barcode (similar as in ZXing)?

**Comment by JimmyPun610** [comment]
Hi. Please try 6.3.0.25, I added BarcodeResult.RawData.
The data is from the rawData that MLKit return
