### ISSUE TITLE
can't install nuget pack 

### ISSUE THREAD

**Issue by daneil30** [JimmyPun610/BarcodeScanner.Mobile#162]
Install-Package : A part of the path could not be found
'C:\Users\Sisinfo01\.nuget\packages\xamarin.firebase.ios.core\8.10.0.1\lib\xamarinios10\Firebase.Core.resources\GoogleUtilitiesComponents.xcframework\ios-arm64_i386_x86_64-simulator\GoogleUtilitiesComponents.framework\Headers\GoogleUtilitiesComponents-umbrella.h'.
In riga:1 car:1
+ Install-Package "C:\Users\Sisinfo01\.nuget\packages\barcodescanner.mo ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Install-Package], Exception
    + FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PackageManagement.PowerShellCmdlets.InstallPackageCommand

**Comment by uabeysinghe** [comment]
Move Nuget installation folder closer to the root:  https://github.com/xamarin/GoogleApisForiOSComponents/issues/555#issuecomment-1145943195

**Comment by JimmyPun610** [comment]
maybe related to https://github.com/JimmyPun610/BarcodeScanner.Mobile/issues/124
