### ISSUE TITLE
Dependency

### ISSUE THREAD

**Issue by EvilPhatBoi** [JimmyPun610/BarcodeScanner.Mobile#169]
Hi there.
I am having trouble getting this to work for my Maui app, targeting iOS on windows.
On Visual Studio for Mac, it works.

I cloned the repo and started upgrading to Core 7.

Is there any chance the 2 packages that are being referenced in the iOS target wil be released on Github?
Xamarin.MLKit.iOS.Core.JimmyPun610
Xamarin.MLKit.iOS.BarcodeScanning.JimmyPun610

Would like to see if they are the reason im getting the "The "ResolveNativeReferences" task failed unexpectedly" error when i try to build on windows.

**Comment by JimmyPun610** [comment]
from previous discussion in #130 , this may be visual studio issue and you may need to use mac to build it directly.

for the libraries, I copied from xamarin github, you can check on https://github.com/xamarin/GoogleApisForiOSComponents
