### ISSUE TITLE
Unbind and Rebind camera 

### ISSUE THREAD

**Issue by OliverDevsCodex** [JimmyPun610/BarcodeScanner.Mobile#173]
How can I achieve the ability to bind and unbind the camera in my mobile application in the same view? 

I am developing an app that involves scanning barcodes on smartphones, including those with built-in hardware scanners. I would like to give users the option to switch between the camera and the built-in scanner. However, I am facing a limitation on certain Android devices where the hardware scanner stops working once the barcode scanner is added to the UI. I have attempted to use Camera.Handler.DisconnectHandler() to disconnect the camera but I am unable to connect the camera again afterwards. 

How can I resolve this issue? 

Thank you.

**Comment by JimmyPun610** [comment]
You may try to remove the camera view and add it again to your page to see if it is working or not
