### ISSUE TITLE
Error for IOS build

### ISSUE THREAD

**Issue by jarvis10211** [JimmyPun610/BarcodeScanner.Mobile#186]
Severity	Code	Description	Project	File	Line	Suppression State
Error		MessagingRemoteException: An error occurred on client Build1647060 while executing a reply for topic xvs/build/16.4.7060/execute-task/HHT_II/e3a44fe002fGetFileSystemEntries
DirectoryNotFoundException: Could not find a part of the path '/Users/devoyslans/Library/Caches/Xamarin/mtbs/builds/HHT_II/e3a44fe33c1109a133fb32541a975e1e5e439b34b3b6a1bcd11e17d76cb25ea0/C:/Nuget/xamarin.firebase.ios.core/8.10.0.3/lib/net6.0-ios15.4/Firebase.Core.resources'.
	HHT_II	C:\Program Files\dotnet\packs\Microsoft.iOS.Sdk\16.4.7060\targets\Xamarin.Shared.Sdk.targets	2019

**Comment by lpierpoint** [comment]
I am also having this issue only on ios, is there any work around??

**Comment by unrateddi** [comment]
I solved it by changing the path that nuget packages getting stored. I think it's a problem with the characters count / path length. 

Setting the system environment variables for nuget to some short path did the trick.

![image](https://github.com/JimmyPun610/BarcodeScanner.Mobile/assets/13433165/efb7cca7-a19e-4824-a499-93be48d90453)

https://learn.microsoft.com/en-us/nuget/consume-packages/managing-the-global-packages-and-cache-folders

https://learn.microsoft.com/en-us/nuget/reference/cli-reference/cli-ref-environment-variables

**Comment by UkeHa** [comment]
The fix provided by @unrateddi doesn't work if you are also using DevExpress components and try to build for iOS as the current workaround to get it to run interferes with this one.

**Comment by JimmyPun610** [comment]
hopefully this is fixed on vs 17.8
