### ISSUE TITLE
Methods could not be found

### ISSUE THREAD

**Issue by profkaygee** [JimmyPun610/BarcodeScanner.Mobile#191]
I am using this nuget package on a windows machine. Trying to instantiate it, I get the following compile-time error:

 The type or namespace name 'Methods' does not exist in the namespace 'BarcodeScanner.Mobile' (are you missing an assembly re
ference?) [TargetFramework=net7.0-maccatalyst]

Its happening on this line:

BarcodeScanner.Mobile.Methods.SetSupportBarcodeFormat(BarcodeFormats.All);

I am using the latest prerelease. Is there a change that was maybe done that has not been updated on the documentation?

**Comment by DelWoodcock** [comment]
I have the same error, I don't plan on using the Mac version, can I just delete it?

**Comment by JimmyPun610** [comment]
try to use something like below to scope the function call in specified platform.
or just remove the unwanted build target in .csproj
```
#if __IOS__
```
