### ISSUE TITLE
InSide Border Control CameraView Not Taking CornerRadius in MAUI iOS

### ISSUE THREAD

**Issue by Sohel3798** [JimmyPun610/BarcodeScanner.Mobile#194]
![WhatsApp Image 2023-07-26 at 12 51 09 PM](https://github.com/JimmyPun610/BarcodeScanner.Mobile/assets/93022175/09781f3d-c948-4d0b-b6e3-038a5d9131be)

             <Border 
                       Grid.Row="2"
                       Padding="0"
                       Stroke="#00FFFFFF"
                       Margin="10,25,10,0"
                       HorizontalOptions="FillAndExpand"
                       VerticalOptions="FillAndExpand">
                    <Border.StrokeShape>
                        <RoundRectangle CornerRadius="20"></RoundRectangle>
                    </Border.StrokeShape>

                     <gv:CameraView
                        IsScanning="True"
                        HorizontalOptions="FillAndExpand"
                        VerticalOptions="FillAndExpand"
                        OnDetected="Camera_OnDetected" 
                        VibrationOnDetected="True"
                        HeightRequest="200"
                        ScanInterval="100" />
                   
                  </Border>

**Comment by Sohel3798** [comment]
I Founded The Way

**Comment by Moret84** [comment]
> I Founded The Way

May I ask you how ?
