### ISSUE TITLE
The "ResolveNativeReferences" task failed unexpectedly when building a iOS app.

### ISSUE THREAD

**Issue by geertgeerits** [JimmyPun610/BarcodeScanner.Mobile#198]
Visual Studio Community 2022 -Version 17.7.2
iPad or iPhone connected to a Mac.

Building an iOS app I get the error: 

**Additional context**
Build started...
1>------ Build started: Project: BarcodeGenerator, Configuration: Debug Any CPU ------
1>Executing SayHello Task to establish a connection to a Remote Server. 
1>			Properties: 
1>				SessionId=ce33843362ffa56a7990e43a4673253e43df5443612eceef7e13b59aafc069d1, 
1>				Addresss=192.168.0.9, 
1>				SshPort=22, 
1>				TcpPort=50791, 
1>				User=geertgeerits, 
1>				AppName=BarcodeGenerator,
1>				VisualStudioProcessId=32276,
1>				ContinueOnDisconnected=False
1>Detected signing identity:
1>  Code Signing Key: "Apple Development: Created via API (KLxxxxxxxx)" (xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx)
1>  Provisioning Profile: "VS: WildCard Development" (xxxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx)
1>  Bundle Id: com.companyname.barcodegenerator
1>  App Id: S6CWMSSJ54.com.companyname.barcodegenerator
1>Skipping analyzers to speed up the build. You can execute 'Build' or 'Rebuild' command to run analyzers.
1>BarcodeGenerator -> C:\Sources\MAUI\BarcodeGenerator\BarcodeGenerator\bin\Debug\net7.0-ios\ios-arm64\BarcodeGenerator.dll
1>C:\Program Files\dotnet\packs\Microsoft.iOS.Sdk\16.4.7089\tools\msbuild\iOS\Xamarin.Shared.targets(137,3): error MSB4018: The "ResolveNativeReferences" task failed unexpectedly.
1>C:\Program Files\dotnet\packs\Microsoft.iOS.Sdk\16.4.7089\tools\msbuild\iOS\Xamarin.Shared.targets(137,3): error MSB4018: System.AggregateException: One or more errors occurred. ---> System.ComponentModel.Win32Exception: The system cannot find the file specified
1>C:\Program Files\dotnet\packs\Microsoft.iOS.Sdk\16.4.7089\tools\msbuild\iOS\Xamarin.Shared.targets(137,3): error MSB4018:    at System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo)
1>C:\Program Files\dotnet\packs\Microsoft.iOS.Sdk\16.4.7089\tools\msbuild\iOS\Xamarin.Shared.targets(137,3): error MSB4018:    at Xamarin.Utils.Execution.<>c__DisplayClass24_1.<RunAsync>b__0() in /Users/builder/azdo/_work/1/s/xamarin-macios/tools/common/Execution.cs:line 103
1>C:\Program Files\dotnet\packs\Microsoft.iOS.Sdk\16.4.7089\tools\msbuild\iOS\Xamarin.Shared.targets(137,3): error MSB4018: --- End of stack trace from previous location where exception was thrown ---
1>C:\Program Files\dotnet\packs\Microsoft.iOS.Sdk\16.4.7089\tools\msbuild\iOS\Xamarin.Shared.targets(137,3): error MSB4018:    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
1>C:\Program Files\dotnet\packs\Microsoft.iOS.Sdk\16.4.7089\tools\msbuild\iOS\Xamarin.Shared.targets(137,3): error MSB4018:    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
1>C:\Program Files\dotnet\packs\Microsoft.iOS.Sdk\16.4.7089\tools\msbuild\iOS\Xamarin.Shared.targets(137,3): error MSB4018:    at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
1>C:\Program Files\dotnet\packs\Microsoft.iOS.Sdk\16.4.7089\tools\msbuild\iOS\Xamarin.Shared.targets(137,3): error MSB4018:    at Xamarin.MacDev.Tasks.XamarinTask.<ExecuteAsync>d__24.MoveNext() in /Users/builder/azdo/_work/1/s/xamarin-macios/msbuild/Xamarin.MacDev.Tasks/Tasks/XamarinTask.cs:line 120
1>C:\Program Files\dotnet\packs\Microsoft.iOS.Sdk\16.4.7089\tools\msbuild\iOS\Xamarin.Shared.targets(137,3): error MSB4018:    --- End of inner exception stack trace ---
1>C:\Program Files\dotnet\packs\Microsoft.iOS.Sdk\16.4.7089\tools\msbuild\iOS\Xamarin.Shared.targets(137,3): error MSB4018:    at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
1>C:\Program Files\dotnet\packs\Microsoft.iOS.Sdk\16.4.7089\tools\msbuild\iOS\Xamarin.Shared.targets(137,3): error MSB4018:    at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
1>C:\Program Files\dotnet\packs\Microsoft.iOS.Sdk\16.4.7089\tools\msbuild\iOS\Xamarin.Shared.targets(137,3): error MSB4018:    at System.Threading.Tasks.Task.Wait()
1>C:\Program Files\dotnet\packs\Microsoft.iOS.Sdk\16.4.7089\tools\msbuild\iOS\Xamarin.Shared.targets(137,3): error MSB4018:    at Xamarin.MacDev.Tasks.ResolveNativeReferencesBase.ProcessSidecar(ITaskItem r, String resources, List`1 native_frameworks) in /Users/builder/azdo/_work/1/s/xamarin-macios/msbuild/Xamarin.MacDev.Tasks/Tasks/ResolveNativeReferencesBase.cs:line 133
1>C:\Program Files\dotnet\packs\Microsoft.iOS.Sdk\16.4.7089\tools\msbuild\iOS\Xamarin.Shared.targets(137,3): error MSB4018:    at Xamarin.MacDev.Tasks.ResolveNativeReferencesBase.Execute() in /Users/builder/azdo/_work/1/s/xamarin-macios/msbuild/Xamarin.MacDev.Tasks/Tasks/ResolveNativeReferencesBase.cs:line 104
1>C:\Program Files\dotnet\packs\Microsoft.iOS.Sdk\16.4.7089\tools\msbuild\iOS\Xamarin.Shared.targets(137,3): error MSB4018:    at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute()
1>C:\Program Files\dotnet\packs\Microsoft.iOS.Sdk\16.4.7089\tools\msbuild\iOS\Xamarin.Shared.targets(137,3): error MSB4018:    at Microsoft.Build.BackEnd.TaskBuilder.<ExecuteInstantiatedTask>d__26.MoveNext()
1>C:\Program Files\dotnet\packs\Microsoft.iOS.Sdk\16.4.7089\tools\msbuild\iOS\Xamarin.Shared.targets(137,3): error MSB4018: ---> (Inner Exception #0) System.ComponentModel.Win32Exception (0x80004005): The system cannot find the file specified
1>C:\Program Files\dotnet\packs\Microsoft.iOS.Sdk\16.4.7089\tools\msbuild\iOS\Xamarin.Shared.targets(137,3): error MSB4018:    at System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo)
1>C:\Program Files\dotnet\packs\Microsoft.iOS.Sdk\16.4.7089\tools\msbuild\iOS\Xamarin.Shared.targets(137,3): error MSB4018:    at Xamarin.Utils.Execution.<>c__DisplayClass24_1.<RunAsync>b__0() in /Users/builder/azdo/_work/1/s/xamarin-macios/tools/common/Execution.cs:line 103
1>C:\Program Files\dotnet\packs\Microsoft.iOS.Sdk\16.4.7089\tools\msbuild\iOS\Xamarin.Shared.targets(137,3): error MSB4018: --- End of stack trace from previous location where exception was thrown ---
1>C:\Program Files\dotnet\packs\Microsoft.iOS.Sdk\16.4.7089\tools\msbuild\iOS\Xamarin.Shared.targets(137,3): error MSB4018:    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
1>C:\Program Files\dotnet\packs\Microsoft.iOS.Sdk\16.4.7089\tools\msbuild\iOS\Xamarin.Shared.targets(137,3): error MSB4018:    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
1>C:\Program Files\dotnet\packs\Microsoft.iOS.Sdk\16.4.7089\tools\msbuild\iOS\Xamarin.Shared.targets(137,3): error MSB4018:    at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
1>C:\Program Files\dotnet\packs\Microsoft.iOS.Sdk\16.4.7089\tools\msbuild\iOS\Xamarin.Shared.targets(137,3): error MSB4018:    at Xamarin.MacDev.Tasks.XamarinTask.<ExecuteAsync>d__24.MoveNext() in /Users/builder/azdo/_work/1/s/xamarin-macios/msbuild/Xamarin.MacDev.Tasks/Tasks/XamarinTask.cs:line 120<---
1>C:\Program Files\dotnet\packs\Microsoft.iOS.Sdk\16.4.7089\tools\msbuild\iOS\Xamarin.Shared.targets(137,3): error MSB4018:
1>Done building project "BarcodeGenerator.csproj" -- FAILED.
========== Build: 0 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========
========== Build started at 18:31 and took 11,225 seconds ==========
========== Deploy: 0 succeeded, 0 failed, 0 skipped ==========
========== Deploy started at 18:31 and took 11,225 seconds ==========

**Comment by rajeshsws** [comment]
I am also facing same Problem. 
Is there any plan for .net 8?

**Comment by rajeshsws** [comment]
upgrade to VS 17.8.0 .my problem solved by upgrading.

**Comment by geertgeerits** [comment]
VS 17.8.0 solved this problem.  Thanks.
