### ISSUE TITLE
.NET 8?

### ISSUE THREAD

**Issue by rehnz** [JimmyPun610/BarcodeScanner.Mobile#207]
I know .NET 8 just was released, but I think it busted my barcode scanner that was working in .NET 7, was wondering if something I blew up, or not supported for .NET 8 yet?

**Comment by JimmyPun610** [comment]
currently working on upgrading it to net 8 and bring in some merged pull request

**Comment by rehnz** [comment]
> currently working on upgrading it to net 8 and bring in some merged pull request

Awesome, great news. Thanks man

**Comment by rajeshsws** [comment]
> currently working on upgrading it to net 8 and bring in some merged pull request

Any time line in your mind?

**Comment by JimmyPun610** [comment]
Just uploaded to nuget but not tested yet.
Any help will be appreciated

**Comment by rajeshsws** [comment]
Thank you very much.

**Comment by rehnz** [comment]
Working on my end, Thanks.
