### ISSUE TITLE
Error updating from BarcodeScanner.Mobile.Maui from 7.0.0.1-pre to 8.0.0

### ISSUE THREAD

**Issue by geertgeerits** [JimmyPun610/BarcodeScanner.Mobile#208]
Updating from BarcodeScanner.Mobile.Maui from 7.0.0.1-pre to 8.0.0
Error: Sequence contains no matching element.

Visual Studio 2022 Version 17.8.0
.NET 8

**Comment by JimmyPun610** [comment]
could you please provide any log or step to reproduce

**Comment by geertgeerits** [comment]
Sorry, my error.
I had this in my project file to exclude the NuGet package in a iOS build:
<PackageReference Include="BarcodeScanner.Mobile.Maui" Version="7.0.0.1-pre" Condition="'$(TargetFramework)'=='net8.0-android'" />

I changed it to this and the update works.
