### ISSUE TITLE
Scanning is not working Release Build with .NET 8 Maui Android

### ISSUE THREAD

**Issue by RayHouston** [JimmyPun610/BarcodeScanner.Mobile#209]
**Describe the bug**
Barcode detection never fires with an Android Release build.

**To Reproduce**
1. Create a new .NET Maui application with BarcodeScanner.Mobile (I had to remove iOS as a target to get it to compile)
2. Add a CameraView and wire up the OnDetectedCommand command to receive the results (I'm using a ViewModel with Binding)
3. Run in Debug to verify it works
4. Run in Release to reproduce the problem

**Expected behavior**
OnDetectedCommand should fire

**Smartphone (please complete the following information):**
 - Device: Android
 - OS: 11, 12, 13
 - Version Maui 8

**Additional context**
Perhaps I have something set wrong. It's working great in a debug build. I first noticed this after building a release build via Azure Pipelines and saw it wasn't working. I've reproduce it locally on various Android devices with Android version 11, 12 and 13 with no luck.
What's a good way to debug this? Thanks!

**Comment by JimmyPun610** [comment]
Just tested on Samsung S23 Ultra and it seems all good

**Comment by RayHouston** [comment]
Hi Jimmy. Thanks for your work on this lib.
Perhaps it's the way I'm using the lib? I've attached a sample project that has the problem.
[maui-barcode.zip](https://github.com/JimmyPun610/BarcodeScanner.Mobile/files/13403680/maui-barcode.zip)

I'm also building on a M1 Mac running Sonoma though I'm sure Azure Pipelines is not running Sonoma.
I'm also using Android API 34.

I've tested  on:
Samsung Galaxy Tab 3
Samsung Galaxy Tab A7
Samsung Galaxy Note20 5G
Samsung Galaxy Note 20 Ultra

Let me know if you think of something to help me debug this issue.
Thank you!

**Comment by RayHouston** [comment]
I believe I'm fighting multiple issues. The missing screen output in Release mode made me believe the detection was not firing. I confirmed the event is firing. This seems to be an issue unrelated to the lib and something to do with Maui and rendering data over the camera view. Sorry for the inconvenience.
