### ISSUE TITLE
Upgrading MLKit dependencies

### ISSUE THREAD

**Issue by dk-mushiyoke** [JimmyPun610/BarcodeScanner.Mobile#225]
Greetings,

We are attempting to use this nuget package alongside MLKit text recognition through own custom binding libraries on iOS. There seems to be version conflicts caused by the MLKit frameworks, where our binding libraries are pulling latest cocoapod versions while this project is using older versions. Would you be willing to upgrade the MLKit dependencies referenced in this project?

Thanks,
DK

**Comment by JimmyPun610** [comment]
May I ask which version are you in?
It was just updated to

- MLKitBarcodeScanning-2.2.0
- MLKCore-8.0.0
- MLImg-1.0.0beta3
- MLKVision-4.2.0
- MLKMDD-4.2.0
It looks there are newer version in the list in MLKit official page (released on 17 April 2024)
But it looks the cocoapod is not available.

**Comment by bengavin** [comment]
@JimmyPun610 - we'll shortly have new versions of the MLKit.BarcodeScanning libraries available from here (https://github.com/AdamEssenmacher/GoogleApisForiOSComponents), if I get a PR put together, any chance we can get that merged in here :)

**Comment by dk-mushiyoke** [comment]
@JimmyPun610 Sorry for late response, we ended up writing our own binding libraries as we needed to use MLKitTextRecoginition library besides the barcode scanning stuff, kudos for updating the dependencies tho!

@bengavin will check out this fork, thanks!

I would close this issue now but I don't want to drop your communication efforts, please feel free to close at your convenience.

**Comment by JimmyPun610** [comment]
closing.
Thanks for the effort from @bengavin
