### ISSUE TITLE
Usage in .net6.0-android (NOT Maui or Xamarin.Forms)

### ISSUE THREAD

**Issue by amirvenus** [JimmyPun610/BarcodeScanner.Mobile#233]
Hi,

I was wondering if anyone's had any experience using this library without maui and when targetting .net6.0-android only (formerly known as Xamarin native)?

Thanks!

**Comment by JimmyPun610** [comment]
The library is for MAUI or Xamarin Forms.
But the 3rd party library (MLKit) is for native, you may still use MLKit in your native app and build the UI part.
Closing since it is not related to the project.
