### ISSUE TITLE
Inquire: Will this package need to update to use the new Apple privacy file?

### ISSUE THREAD

**Issue by WanftMoon** [JimmyPun610/BarcodeScanner.Mobile#235]
Seeing that we are nearing the point where Apple will require apps and third party libraries to use their privacy files (https://developer.apple.com/documentation/bundleresources/privacy_manifest_files).
Will this package need it?

**Comment by JimmyPun610** [comment]
Probably yes...
Will try to arrange some time for it...
https://devblogs.microsoft.com/dotnet/apple-privacy-manifest-support/

**Comment by WanftMoon** [comment]
> Probably yes... Will try to arrange some time for it... https://devblogs.microsoft.com/dotnet/apple-privacy-manifest-support/

please, consider updating the xamarin version as well.

**Comment by mos379** [comment]
T-4 days!

**Comment by JimmyPun610** [comment]
Just updated the version to include it. But I am lack of resource to test if it is work or not...
Please let me know if there is any feedback from Apple...

**Comment by WanftMoon** [comment]
> Just updated the version to include it. But I am lack of resource to test if it is work or not... Please let me know if there is any feedback from Apple...

I'm not sure that adding it to the nuget package is the solution. As I could understand, the issue is because iOS uses MLKIT and Firebase.Core newest versions have them. So, it would require the iOS native bindings to be updated.

**Comment by JimmyPun610** [comment]
> > Just updated the version to include it. But I am lack of resource to test if it is work or not... Please let me know if there is any feedback from Apple...
> 
> 
> 
> I'm not sure that adding it to the nuget package is the solution. As I could understand, the issue is because iOS uses MLKIT and Firebase.Core, and the newest versions have the privacy manifests. So, it would require the iOS native bindings to be updated.
> 
> 
> 
> For firebase, we have versions for 10.18 (ideally should be 10.22). But Adam is working his way up there at fast pace
> 
> https://github.com/AdamEssenmacher/GoogleApisForiOSComponents/issues/2

For the latest version, I have also updated the version of the binding library and removed the Firebase.Core dependence(Hopefully it will still work).

Google has updated their native library on 17 April 2024 to address the privacy issue, but it looks I do not find it in cocoapad for now...

**Comment by bengavin** [comment]
This should be fixed in the latest versions
