### ISSUE TITLE
Hi, can we use that nuget on a .Net 8 for iOS project (Not MAUI) ?

### ISSUE THREAD

**Issue by jbouche-work** [JimmyPun610/BarcodeScanner.Mobile#238]
Hi, 

can we use that nuget on a ".Net 8 for iOS" project (Not MAUI) ?
And how can we use it ?

Before make the migration form Xamarin native for iOS to .NET 8 for iOS, I was using ZXing.Net.Mobile and the MobileBarcodeScanner util.

If not, do you know another nuget who can do the job ?

Sincerly

**Comment by bengavin** [comment]
Out of curiosity, while toolkit are you using for .NET 8 iOS development that isn't MAUI?

**Comment by jbouche-work** [comment]
> Out of curiosity, [??? what ???] toolkit are you using for .NET 8 iOS development that isn't MAUI?

Hi, I'm using the new Xamarin Native => .Net for iOS.
With MVVMCross for the IOC.

**Comment by bengavin** [comment]
If you can integrate with the native camera to capture pictures, you can always use the MLKit barcode scanning functionality directly.  We're working through getting a working version published under the 'AdamE.MLKit.iOS.BarcodeScanning' package now [note the alpha1 package is missing some dependencies and won't yet work].

**Comment by JimmyPun610** [comment]
unfortunately the library does not support .net ios (former xamarin.ios). You could have a use the
