### ISSUE TITLE
please help me

### ISSUE THREAD

**Issue by bangnguyen794** [JimmyPun610/BarcodeScanner.Mobile#56]
Why can't the scanner read this qrcode? Is this an error or unsupported format.
<img width="667" alt="Ảnh chụp Màn hình 2021-03-26 lúc 09 39 50" src="https://user-images.githubusercontent.com/17409119/112569679-3769ba80-8e17-11eb-9ed5-85e2dc5f1f41.png">

**Comment by JimmyPun610** [comment]
Hi @bangnguyen794 

It looks working on my Pixel 3 with the sample app.
![Screenshot_20210326-104900](https://user-images.githubusercontent.com/12612781/112570677-7b61bd00-8e21-11eb-9492-672b17ad43e4.png)

**Comment by JimmyPun610** [comment]
closed due to no response for a week

**Comment by bangnguyen794** [comment]
I'm sorry, I didn't see the message, it happened on iOS.

https://user-images.githubusercontent.com/17409119/113507406-5cc39a80-9574-11eb-910f-456e10b4fe13.mp4

**Comment by JimmyPun610** [comment]
> I'm sorry, I didn't see the message, it happened on iOS.
> 
>  Phim.c.a.toi.4.mp4

I just tested on my iPhone 11 with the sample app and it looks also working.
could you provide your code snippet for your implementation?

https://user-images.githubusercontent.com/12612781/113647461-71f81080-96bd-11eb-921e-0e709ec1a623.mp4

**Comment by bangnguyen794** [comment]
I download souce from github (https://github.com/JimmyPun610/BarcodeScanner.XF) run a test ..

https://user-images.githubusercontent.com/17409119/113655443-01a0bd80-96c4-11eb-8ee2-1f1abc8c2792.mp4

**Comment by JimmyPun610** [comment]
I tried that it would work in some angle, but still hard to scan the code.
It may caused by the quality of the qrcode and the scanning engine.
I could only suggest you try to set the barcode type to QRCode.

Does it happens on other qrcodes with similar texture?

**Comment by bangnguyen794** [comment]
I set the barcode type to Qrcode, it doesn't yield better results. [ **Methods.SetSupportBarcodeFormat(BarcodeFormats.QRCode);** ]
I used the scanner on the iphone it produced the expected results.
 Does it happens on other qrcodes with similar texture? => yes.
I look forward to an update that improves qrcode scanning. Thanks **JimmyPun610**
