### ISSUE TITLE
Camera crashes on Android

### ISSUE THREAD

**Issue by Dindexx** [JimmyPun610/BarcodeScanner.Mobile#94]
Hi there,

i am observing the following crash at times when im using the BarcodeScanner: 

CameraViewRenderer+BarcodeAnalyzer.Analyze (AndroidX.Camera.Core.IImageProxy proxy)
System.ArgumentException: Handle must be valid. Parameter name: instance

with the following StackTrace:

JniEnvironment+InstanceMethods.CallVoidMethod (Java.Interop.JniObjectReference instance, Java.Interop.JniMethodInfo method)
JNIEnv.CallVoidMethod (System.IntPtr jobject, System.IntPtr jmethod)
IImageProxyInvoker.Close ()
CameraViewRenderer+BarcodeAnalyzer.Analyze (AndroidX.Camera.Core.IImageProxy proxy)
AsyncMethodBuilderCore+<>c.<ThrowAsync>b__7_1 (System.Object state)
QueueUserWorkItemCallback.WaitCallback_Context (System.Object state)
ExecutionContext.RunInternal (System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, System.Object state, System.Boolean preserveSyncCtx)
ExecutionContext.Run (System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, System.Object state, System.Boolean preserveSyncCtx)
IThreadPoolWorkItem.ExecuteWorkItem ()
ThreadPoolWorkQueue.Dispatch ()
_ThreadPoolWaitCallback.PerformWaitCallback ()

I am using the preview version 6.1 where the SafeCloseImageProxy() method is missing in the BarcodeAnalyzer class in BarcodeScanner.XF/GoogleVisionBarCodeScanner/Android/Renderer/CameraViewRenderer.cs. The SafeCloseImageProxy() method is available in the master branch and i think my issue will be resolved if this also will be added/merged for 6.1

Thanks a lot in advance!

**Comment by JimmyPun610** [comment]
Just uploaded version 6.1.1-pre.
Pretty sure that logic is in this version.
